"""Add user_id to titles

Revision ID: 99501d436713
Revises: 6689dc296fb4
Create Date: 2025-06-03 18:05:04.556395

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99501d436713'
down_revision = '6689dc296fb4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('titles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('fk_titles_user_id_user', 'user', ['user_id'], ['id'])


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('titles', schema=None) as batch_op:
        batch_op.drop_constraint('fk_titles_user_id_user', type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
